#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qpid-tools
Version  : 1.36.0.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/c1/2d/faf3a1956c5b28432fb96ef922089979a65e89b073e1bbfec6e012c7871a/qpid-tools-1.36.0-1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c1/2d/faf3a1956c5b28432fb96ef922089979a65e89b073e1bbfec6e012c7871a/qpid-tools-1.36.0-1.tar.gz
Summary  : Python libraries for the Apache Qpid C++ broker
Group    : Development/Tools
License  : Apache-2.0
Requires: qpid-tools-license = %{version}-%{release}
Requires: qpid-python
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : python3
BuildRequires : qpid-python

%description
# Python libraries for the Apache Qpid C++ broker
        
        ## qmf
        
        The Qpid Management Framework (QMF).
        
        ## qpidtoollibs
        
        A high-level BrokerAgent object for managing the C++ broker using QMF.
        
        This library depends on the qpid.messaging python client to send AMQP
        messages containing QMF commands to the broker.

%package license
Summary: license components for the qpid-tools package.
Group: Default

%description license
license components for the qpid-tools package.


%prep
%setup -q -n qpid-tools-1.36.0-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545532521
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1545532521
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qpid-tools
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/qpid-tools/LICENSE.txt
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qpid-tools/LICENSE.txt
